sudo: required
services:
  - docker

before_isntall:
  - docker build -t rkreddy78/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true rkreddy78/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-204756260376"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY